export const DIRECTION_EIGHT = [
  {detail:`DISHA RULING PLANET : MERCURY
  DISHA PALAK DIETY : KUBER
  DISHA PALAK VEHICLE : WHITE HORSE
  DISHA PALAK WEAPON : GADA
  ASTHLAKSHMI : DHANLAKSHMI
  COLOUR : GREEN
  North direction represent Money or Treasure and New opportunities.`,
hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`
},

  {detail:`DISHA RULING PLANET : JUPITER
  DISHA PALAK DIETY : SHIVA / ISHAAN
  DISHA PALAK VEHICLE : VRASHABH
  DISHA PALAK WEAPON : TRISHUL
  ASTHLAKSHMI : SANTAAN LAKSHAMI
  COLOUR : YELLOW
  It is the Zone of Wisdom, Meditation and Inspiration. 
  In Vastu, this Zone is ideal for Meditation.`,
  hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},

  {detail:`DISHA RULING PLANET : SUN
  DISHA PALAK DIETY : INDRA
  DISHA PALAK VEHICLE : 
  DISHA PALAK WEAPON : VAJRAYUDH
  ASTHLAKSHMI : AISHWARYA LAKSHMI
  COLOUR : WHITE
  The energy generated by East Zone facilitates the Social Connectivity. 
  It is the ideal Zone for a Drawing Room.`,
  hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},

  {detail:`DISHA RULING PLANET : VENUS
  DISHA PALAK DIETY : AGNIDEV
  DISHA PALAK VEHICLE : BAKRA
  DISHA PALAK WEAPON : SHAKTI
  ASTHLAKSHMI : DHANLAKSHMI
  COLOUR : BROWN, MULTI COLOUR
  South East Direction is responsible for good health and healthy finanace.`,
  hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},

  {detail:`DISHA RULING PLANET : MARS
  DISHA PALAK DIETY : YAM
  DISHA PALAK VEHICLE : MAHISH
  DISHA PALAK WEAPON : KAALPAASH
  ASTHLAKSHMI : AADILAKSHMI
  COLOUR : RED
  Most importantly, this is the Zone of Fame, Recognition and Social Reputation.`,
  hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`
},

  {detail:`DISHA RULING PLANET : RAHU
  DISHA PALAK DIETY : NAIRUTI
  DISHA PALAK VEHICLE : NAR (MANUSHAYA)
  DISHA PALAK WEAPON : SWORD
  ASTHLAKSHMI : DHAIRYA LAKSHAMI
  COLOUR : SMOOKY
  It is the direction of Skill, Marriage, Family Harmony, 
  Bonding, Stability in life and Relationships.`,
  hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},

  {detail:`DISHA RULING PLANET : SATURN
  DISHA PALAK DIETY : VARUN DEV
  DISHA PALAK VEHICLE : CROCODILE (MAGAR)
  DISHA WEAPON : PAASH
  ASTHLAKSHMI : GAJ LAKSHMI
  COLOUR : BLACK
  The West direction is capable of giving success, glory, fame and fortune. 
  The energy of this Zone ensures that no action or effort made by you goes waste.`,
  hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},

 { detail:`DISHA RULING PLANET : MOON
  DISHA PALAK DIETY : VAAYU DEV
  DISHA PALAKVEHICLE : HIRAN ( DEER)
  DISHA PALAK WEAPON : ANKUSH
  ASTHLAKSHMI : VIJAY LAKSHMI
  COLOUR : WHITE
  The North West is responsible for relationsships, friends, enemies and 
  support system.The North-West Zone generates the energy that attracts Supportive 
  and Helpful people for any cause you pursue`,
  hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},
];

export const DIRECTION_SIXTEEN = [
{detail:`ATTRIBUTE : MONEY AND OPPORTUNITIES
  ELEMENT : WATER
  IT COVERS -
  BHALLAT spread over 2 padas of Pishach Vithi & Manushya Vithi(N4)
  SOMA-spread over 2 padas of Pishach Vithi & Manushya Vithi (N5) 
  BHUDHAR-occupies Dev Vithi
  `,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},
{detail:`ATTRIBUTE : HEALTH AND IMMUNITY
  ELEMENT : WATER
  IT COVERS -
  BHUJANG spread over 2 padas of Pishach Vithi & Manushya Vithi(N6)
  ADITI-spread over 1 pada of Pishach Vithi(N7) 
  APA occupies Manushya Vithi 
  BHUDHAR-occupies Dev Vithi
  `,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},
{detail:`ATTRIBUTE : CLARITY OF MIND
  ELEMENT : WATER
  IT COVERS -
  DITI spread over 1 pada of Pishach Vithi(N8) 
  APA occupies Manushya Vithi & BHUDHAR occupies Dev Vithi 
  SHIKHI -spread over 1 pada of Pishach Vithi(E1)
  APAVATSA occupies Manushya Vithi & ARYAMA in Dev Vithi
  `,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},
{detail:`ATTRIBUTE : RECREATION AND FUN
  ELEMENT : AIR
  IT COVERS -
  PARJANYA - spread over 1 pada of Pishach Vithi(E2)
  APAVATSA occupies Manushya Vithi & ARYAMA in Dev Vithi ,
  JAYANTA -spread over 2 padas of Pishach Vithi & Manushya Vithi(E3)
  ARYAMA in Dev Vithi
  `,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},
{detail:`ATTRIBUTE : SOCIAL ASSOCIATION
  ELEMENT : AIR
  IT COVERS -
  INDRA- spread over 2 padas of Pishach Vithi & Manushya Vithi(E4),
  RAVI-spread over 2 padas of Pishach Vithi & Manushya Vithi(E5)
  ARYAMA in Dev Vithi
  `,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},
{detail:`ATTRIBUTE : ANXIETY AND ANALYSIS
  ELEMENT : AIR
  IT COVERS -
  SATYA- spread over 2 padas of Pishach Vithi & Manushya Vithi(E6), 
  BHRISH-spread over 1 pada of Pishach Vithi(E7), 
  SAVITA occupies Manushya Vithi, 
  ARYAMA in Dev Vithi
  `,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},
{detail:`ATTRIBUTE : CASH FLOW
  ELEMENT : FIRE
  IT COVERS -
  AKASH- spread over 1 pada of Pishach Vithi(E8)
  SAVITA occupies Manushya Vithi 
  ARYAMA occupies Dev Vithi
  ANIL-spread over 1 pada of Pishach Vithi(S1)
  SOSHA occupies Manushya Vithi 
  VIVASVAN in Dev Vithi
  `,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},
{detail:`ATTRIBUTE : POWER AND CONFIDENCE
  ELEMENT : FIRE
  IT COVERS -PUSHA- spread over 1 pada of Pishach Vithi(S2,)
  SOSHA occupies Manushya Vithi
  VIVASVAN in Dev Vithi
  VITATHA-spread over 2 padas of Pishach Vithi & Manushya Vithi(S3)
  VIVASVAN in Dev Vithi
  `,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},
{detail:`ATTRIBUTE : REST, RELAXATION AND FAME
  ELEMENT : FIRE
  IT COVERS -GRIHAKSHAT- spread over 2 padas of Pishach Vithi & Manushya Vithi(S4)
  YAMA - spread over 2 padas of Pishach Vithi & Manushya Vithi(S5)
  VIVASVAN in Dev Vithi
  `,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},
{detail:`ATTRIBUTE : EXPENDITURE AND WASTAGE
  ELEMENT : EARTH
  IT COVERS -
  GANDHARVA- spread over 2 padas of Pishach Vithi & Manushya Vithi(S6)
  BHRINGARAJ- spread over 1 pada of Pishach Vithi(S7), INDRA occupies Manushya Vithi,
  VIVASVAN in Dev Vithi
  `,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},
{detail:`ATTRIBUTE : RELATIONSHIP AND SKILLS
  ELEMENT : EARTH
  IT COVERS -
  MRIGA- spread over 1 pada of Pishach Vithi(S8),
  INDRA occupies Manushya Vithi
  VIVASVAN occupies Dev Vithi, 
  PITRI- spread over 1 pada of Pishach Vithi(W1),
  JAYA occupies Manushya Vithi 
  MITRA in Dev Vithi
  `,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},
{detail:`ATTRIBUTE : EDUCATIONS AND SAVINGS
  ELEMENT : SPACE
  IT COVERS -
  DAUVARIK- spread over 1 pada of Pishach Vithi(W2)
  JAYA occupies Manushya Vithi
  MITRA in Dev Vithi
  SUGRIVA- spread over 2 padas of Pishach Vithi & Manushya Vithi(W3) 
  MITRA in Dev Vithi
  `,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},
{detail:`ATTRIBUTE : GAINS AND PROFITS
  ELEMENT : SPACE
  IT COVERS -
  PUSHPADANT- spread over 2 padas of Pishach Vithi & Manushya Vithi(W4), 
  VARUN- spread over 2 padas of Pishach Vithi & Manushya Vithi(W5), 
  MITRA in Dev Vithi
  `,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},
{detail:`ATTRIBUTE : DEPRESSION
  ELEMENT : SPACE
  IT COVERS -
  ASURA- spread over 2 padas of Pishach Vithi & Manushya Vithi(W6),
  SOSHA- spread over 1 pada of Pishach Vithi(W7), 
  RUDRA occupies Manushya Vithi, 
  MITRA in Dev Vithi
  `,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},
{detail:`ATTRIBUTE : SUPPORT AND BANKING
  ELEMENT : EARTH
  IT COVERS -
  PAPA YAKSHMA - spread over 1 pada of Pishach Vithi(W8), RUDRA occupies Manushya Vithi 
  MITRA occupies Dev Vithi, 
  ROGA- spread over 1 pada of Pishach Vithi(N1), RAJYAKSHAMA occupies Manushya Vithi 
  BHUDHAR in Dev Vithi
  `,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},
{detail:`ATTRIBUTE : ATTRACTION AND SEX
  ELEMENT :WATER
  IT COVERS -
  NAGA - spread over 1 pada of Pishach Vithi(N2), RAJYAKSHAMA occupies Manushya VithI
  BHUDHAR in Dev Vithi, 
  MUKHYA- spread over 2 padas of Pishach Vithi & Manushya Vithi(N3), 
  BHUDHAR in Dev Vithi
  `,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},
];

export const DIRECTION_THIRTYTWO = [
  {detail:`The Entrance Ensures Abundance Of Money, Inherited And / Or Earned.`,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},

 {detail: `This Entrance Makes People Religious, Non-aggressive And Calm.`,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},

  {detail:`The Entrance Makes Residents Behave In A Manner That People Generally 
  Disapprove Of. People Usually Avoid Listening To Them.`,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},

 {detail: `This Entrance Instigates Rebellious Attitude Among Young Girls And Makes 
  Them Go Against The Family’s Culture And Social Beliefs. In The Indian Context, 
  A Girl In Such A Family May Resort To An Inter Caste Marriage.`,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},

 {detail: `Such A Entrance Paves Way For A Higher Bank Balance For Its Occupants.`,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},

  {detail:`This Entrance Causes Fire Accidents And Unexpected Losses`,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},

 {detail: `This Entrance Induces Wasteful Expenditure. For An Expecting Mother, 
  It Will Increase The Probability Of Birth Of Baby.`,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},

  {detail:`This Is An Auspicious Zone Entrance Which Brings Money, Profits And Overall Success`,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},

  {detail:`This Entrance Helps The Inhabitants Build Beneficial And Close Association With 
  Government Officials Or With Those In Authority`,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},

  {detail:`This Entrance Makes People Extremely Short-tempered, Bordering On Insanity At Times.`,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},

  {detail:`This Entrance Makes It Difficult For People To Keep Their Word Making Them Appear Unreliable.`,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},

  {detail:`People Of Such Houses Become Insensitive Towards The Problems Of Other People.`,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},

  {detail:`This Entrance Paves Way For Accidents, Financial Losses, Burglary And Other Such Problems.`,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},

  {detail:`This Entrance Negatively Impacts Children, Especially The Boys Of The House. Their Actions Go 
  Against Their Parents Expectations.`,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},

  {detail:`This Entrance Increase The Tendency To Work For Others. It Is Good For People Working In M Or Similar Setups,`,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},

  {detail:`This Entrance Brings Immense Prosperity. The Occupants Of Such A House Become Smarter And Their Work Gets Done Easily`,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},

  {detail:`Industries In Such Plots Are Highly Successful. The Family Residing In Such A Space Is Bless With More Sons.`,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},

  {detail:`The People In Such Houses Are Rarely Free From Debts. They Feel Incapable Of Making Good Use Of Their Intellect.`,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},

  {detail:`A Door Abysmal Poverty`,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},

  {detail:`People Residing In Such Houses Suffer, As Their Efforts Towards A Profession Or Relationship Keep Going Waste. They Remain Disconnected And Unhappy.`,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},

  {detail:`The Most Ominous Entrance, It Results In Such Behaviour And Attitude, Which Gradually Disconnects The Family From The Rest Of The World, 
  Thereby Severely Affecting Their Finance And Relationships,`,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},

  {detail:`This Entrance IS NEGATIVE FOT THE RESIDENTS Financial Position And Life Span`,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},

  {detail:`The Entrance Creates Instability In Career. People Residing Here Lack Clarity Of Thought And Vision. They Turn Insure, Especially Of 
  Their Near And Dear Ones.`,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},

  {detail:`This Entrance Brings Astounding Growth And Prosperity.`,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},

  {detail:`It Offers No Particular Benefits Or Harms. Life In Such Houses Is Generally Smooth. Overall It Is Good Entrance.`,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},

  {detail:`The Entrance Makes One A Perfectionist To The Extent Of Becoming Delusional And Overambitious. One Starts Expecting Unrealistic Gains.`,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},

  {detail:`This Entrance Makes People Prone To Mental Depression.`,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},

  {detail:`An Entrance In This Zone Causes Loss Of General Happiness In The House. At Times, It Induces The Person To Resort To Drugs And Alcohol.`,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},

  {detail:`This Entrance Affects The Mentality Of Residents In Such A Way That They Do Not Mind Adopting Unfair And Unlawful Means For Their Own Benefit.`,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},

  {detail:`In Such A House, The Inhabitants Becomes Susceptible To Harm Caused By Bad Intentions Of Other People.`,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},

  {detail:`A Fear Of Enemies, That Is Not Entirely Unfounded, Stalks People Living In Such Houses, Residents Feel That Others Are Jealous Of Them.`,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},

  {detail:`This Door Bring Lots Of Money And Male Progeny For Those Who Occupy It.`,hindiDetail: `हिंदी में डिस्क्रिप्शन शो होगा।`},
];

